[package]
name = "normalize"
version = "0.1.0"
authors = ["Kartik Thakore <kthakore@alumni.uwo.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
