//! Automatically generated by rune. DO NOT EDIT!

#![no_std]
#![feature(alloc_error_handler)]

extern crate alloc;

#[allow(unused_imports)]
use runic_types::{
    wasm32::{intrinsics, Model, Random, Serial},
    Source, Sink, Transform, debug,
};
use alloc::boxed::Box;

static mut PIPELINE: Option<Box<dyn FnMut()>> = None;

#[no_mangle]
pub extern "C" fn _manifest() -> u32 {
    let mut rand = runic_types::wasm32::Random::default();
    let mut sine = Model::load(include_bytes!("sine.tflite"));
    let mut mod360 = modulo::Modulo::default()
        .with_modulus(360.0)
    ;
    let mut serial = Serial::default();

    let pipeline = move || {
        let data: [f32; 1] = rand.generate();
        runic_types::debug!("rand => {:?}", data);
        let data = mod360.transform(data);
        runic_types::debug!("mod360 => {:?}", data);
        let data: [f32; 1] = sine.transform(data);
        runic_types::debug!("sine => {:?}", data);
        
        serial.consume(data);
    };

    unsafe {
        PIPELINE = Some(Box::new(pipeline));
    }

    1
}

#[no_mangle]
pub extern "C" fn _call(
    _capability_type: i32,
    _input_type: i32,
    _capability_idx: i32,
) -> i32 {
    unsafe {
        let pipeline = PIPELINE.as_mut()
            .expect("The rune hasn't been initialized");
        pipeline();

        0
    }
}
