[package]
name = "rune"
version = "0.2.0"
authors = ["Kartik Thakore <kartik@thakore.ai>", "Akshay Sharma <akshay@sharma.ai>"]
edition = "2018"
license = "Apache 2.0"
keywords = ["tinyml", "container"]


[dependencies]
runefile-parser = { path = "../runefile-parser" }
runic-types = { path = "../runic-types" }
cargo = "0.47.0"
clap = "2.33.3"
env_logger = "0.8.1"
log = "0.4.11"
rand = "0.7.3"
runic-transform = { path = "../runic-transform" }
wasmer-runtime = "0.17.1"
wasmer-runtime-core = "0.17.1"
tflite = "0.9.2"
anyhow = "1.0.38"

