[package]
name = "fft"
version = "0.1.0"
authors = ["Kartik Thakore <kartik@thakore.ai"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libm = "0.2.1"
num-complex = { version = "0.4.0", default-features = false, features = ["libm"] }
runic-types = { path = "../../runic-types" }
