[package]
name = "fft"
version = "0.1.0"
authors = ["Meelis Lootus <meelis@hotg.ai>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
runic-types = { git="ssh://github.com/hotg-ai/rune.git", path="runic_types", branch="feature/gesture_normalized"}
hound = "3.4"
sonogram = {git = "ssh://git@github.com/hotg-ai/sonogram"}

[dev-dependencies]
