//! Automatically generated by rune. DO NOT EDIT!

#![no_std]
#![feature(alloc_error_handler)]

extern crate alloc;

#[allow(unused_imports)]
use runic_types::{
    wasm32::{intrinsics, Model, Random, Serial},
    Source, Sink, Transform, debug,
};
use alloc::boxed::Box;

static mut PIPELINE: Option<Box<dyn FnMut()>> = None;

#[no_mangle]
pub extern "C" fn _manifest() -> u32 {
    let mut image = runic_types::wasm32::Image::default();
    image
        .set_parameter("sampling_frequency_ms", 500);
    let mut person_detection = Model::load(include_bytes!("person_detection.tflite"));
    let mut person_detection_agg = person_detection_agg::PersonDetectionAgg::default()
        .with_labels(["unknown", "person_prob", "not_person_prob"])
    ;
    let mut serial = Serial::default();

    let pipeline = move || {
        let data: [[u8; 96]; 96] = image.generate();
        runic_types::debug!("image => {:?}", data);
        let data: [u8; 3] = person_detection.transform(data);
        runic_types::debug!("person_detection => {:?}", data);
        let data: &'static str = person_detection_agg.transform(data);
        runic_types::debug!("person_detection_agg => {:?}", data);
        
        serial.consume(data);
    };

    unsafe {
        PIPELINE = Some(Box::new(pipeline));
    }

    1
}

#[no_mangle]
pub extern "C" fn _call(
    _capability_type: i32,
    _input_type: i32,
    _capability_idx: i32,
) -> i32 {
    unsafe {
        let pipeline = PIPELINE.as_mut()
            .expect("The rune hasn't been initialized");
        pipeline();

        0
    }
}
