#!/bin/sh
#echo "Install wasm tools from: https://github.com/WebAssembly/binaryen/releases/tag/version_98"
echo "Deploying Rune: rune-rs:latest"
cargo +nightly build --target wasm32-unknown-unknown --release &> /dev/null


echo "Optimizing Rune: rune-rs:latest"
wasm-opt -O3 target/wasm32-unknown-unknown/release/rune.wasm -o app.rune

# wasm-strip app.rune