on:
  push:
    - master
  pull_request:
    - master

name: API Docs

jobs:
  api-docs:
    name: Publish API Docs to GitHub Pages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - nightly
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --all --verbose
      - name: Redirect top-level GitHub Pages
        run: "echo '<meta http-equiv=\"refresh\" content=\"0; url=rune/index.html\" />' > target/doc/index.html"
        shell: bash
      - name: GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc
